/**
 * Automated source tool audit script.
 * Produces data/source-inventory.json from deliberate audits of:
 * - WebTools (https://www.wtoolskit.com/zh/)
 * - 91AI Tools (https://www.91aitool.cn/)
 * - 100016 (https://100016.com/)
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

export interface SourceToolItem {
  id: string;
  name: string;
  category: string;
  url: string;
  description: string;
  inputFormats?: string[];
  outputFormats?: string[];
  processingMode?: "local" | "server" | "external" | "unknown";
  free: boolean;
  requiresAuth: boolean;
}

export interface SourceCatalog {
  name: string;
  url: string;
  status: "active" | "inactive" | "unreachable";
  auditNotes: string;
  tools: SourceToolItem[];
}

export interface MasterSourceInventory {
  generatedAt: string;
  sources: SourceCatalog[];
}

const WEBTOOLS_ITEMS: SourceToolItem[] = [
  // Developer & Data
  {
    id: "json",
    name: "JSON 格式化",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/json/",
    description: "格式化、压缩、验证 JSON",
    inputFormats: ["json"],
    outputFormats: ["json"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "json-repair",
    name: "JSON 修复",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/json-repair/",
    description: "JSON 错误分析与自动修复",
    inputFormats: ["json", "text"],
    outputFormats: ["json"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "base64",
    name: "Base64 编解码",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/base64/",
    description: "Base64 编码与解码转换",
    inputFormats: ["text", "file"],
    outputFormats: ["text", "file"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "url",
    name: "URL 编解码",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/url/",
    description: "URL 编解码与参数解析",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "html-entity",
    name: "HTML实体编解码",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/html-entity/",
    description: "HTML 字符实体编码与解码",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "number-base",
    name: "进制转换",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/number-base/",
    description: "二/八/十/十六进制互转",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "json-yaml",
    name: "JSON/YAML 互转",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/json-yaml/",
    description: "JSON 与 YAML 格式互转",
    inputFormats: ["json", "yaml"],
    outputFormats: ["json", "yaml"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "xml-json",
    name: "XML/JSON 转换",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/xml-json/",
    description: "XML 与 JSON 互转",
    inputFormats: ["xml", "json"],
    outputFormats: ["xml", "json"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "csv-json",
    name: "CSV/JSON 互转",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/csv-json/",
    description: "CSV 与 JSON 格式互转",
    inputFormats: ["csv", "json"],
    outputFormats: ["csv", "json"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-base64",
    name: "图片Base64互转",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/image-base64/",
    description: "图片与 Base64 Data URI 互相转换",
    inputFormats: ["image", "text"],
    outputFormats: ["text", "image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "qrcode",
    name: "二维码生成与解析",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/qrcode/",
    description: "生成/解析二维码",
    inputFormats: ["text", "image"],
    outputFormats: ["png", "svg", "text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "json-path",
    name: "JSONPath 查询",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/json-path/",
    description: "JSONPath 表达式评估与提取",
    inputFormats: ["json", "text"],
    outputFormats: ["json"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "json-schema-generator",
    name: "JSON Schema 生成器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/json-schema-generator/",
    description: "根据 JSON 数据推导 JSON Schema",
    inputFormats: ["json"],
    outputFormats: ["json"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "regex",
    name: "正则测试",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/regex/",
    description: "正则表达式测试与匹配高亮",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "regex-cheat-sheet",
    name: "正则速查",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/regex-cheat-sheet/",
    description: "正则表达式常用语法速查",
    inputFormats: [],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "regex-visualizer",
    name: "正则可视化",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/regex-visualizer/",
    description: "正则表达式铁路图可视化",
    inputFormats: ["text"],
    outputFormats: ["svg"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "code",
    name: "代码格式化",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/code/",
    description: "JS/HTML/CSS 代码美化与压缩",
    inputFormats: ["code"],
    outputFormats: ["code"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "html-preview",
    name: "HTML 预览",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/html-preview/",
    description: "HTML/CSS/JS 实时沙箱预览",
    inputFormats: ["html"],
    outputFormats: ["preview"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "sql-formatter",
    name: "SQL 格式化",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/sql-formatter/",
    description: "SQL 美化与格式整理",
    inputFormats: ["sql"],
    outputFormats: ["sql"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "csv-viewer",
    name: "CSV/Excel 查看器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/csv-viewer/",
    description: "查看和浏览 CSV、Excel 文件表格",
    inputFormats: ["csv", "xlsx"],
    outputFormats: ["table"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "sqlite-viewer",
    name: "SQLite 查看器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/sqlite-viewer/",
    description: "浏览器本地查看 SQLite 数据库文件",
    inputFormats: ["sqlite", "db"],
    outputFormats: ["table"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "html-table-generator",
    name: "表格生成器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/html-table-generator/",
    description: "生成 HTML/Markdown 表格代码",
    inputFormats: ["data"],
    outputFormats: ["html", "markdown"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "meta-tag-generator",
    name: "Meta 标签生成器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/meta-tag-generator/",
    description: "生成 SEO & Open Graph Meta 标签",
    inputFormats: ["options"],
    outputFormats: ["html"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "favicon-generator",
    name: "Favicon 生成器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/favicon-generator/",
    description: "从图片生成多尺寸 Favicon 图标与 ICO",
    inputFormats: ["image"],
    outputFormats: ["ico", "png"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "uuid",
    name: "UUID 生成器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/uuid/",
    description: "批量生成 UUID v4/v7",
    inputFormats: ["options"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "jwt",
    name: "JWT 编解码",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/jwt/",
    description: "JWT Token 解析、签名验证与生成",
    inputFormats: ["jwt", "json"],
    outputFormats: ["json", "text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "cron",
    name: "Cron 表达式解析",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/cron/",
    description: "Cron 表达式解析与运行时间推算",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "timestamp",
    name: "时间戳转换",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/timestamp/",
    description: "Unix 时间戳与本地时间互相转换",
    inputFormats: ["text", "number"],
    outputFormats: ["text", "number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "git-cheat-sheet",
    name: "Git 速查",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/git-cheat-sheet/",
    description: "Git 命令速查手册",
    inputFormats: [],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "markdown",
    name: "Markdown 预览",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/markdown/",
    description: "Markdown 实时编辑与预览",
    inputFormats: ["markdown"],
    outputFormats: ["html"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "lorem",
    name: "占位文本生成",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/lorem/",
    description: "Lorem Ipsum 随机占位文本生成",
    inputFormats: ["options"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "diff",
    name: "文本对比",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/diff/",
    description: "逐行对比两份文本或代码的差异",
    inputFormats: ["text"],
    outputFormats: ["diff"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "device-tester",
    name: "设备检测",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/device-tester/",
    description: "测试麦克风、摄像头、扬声器和屏幕",
    inputFormats: [],
    outputFormats: ["status"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unicode",
    name: "Unicode 字符查询",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/unicode/",
    description: "Unicode 编码查询与字符互转",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "mime",
    name: "MIME 类型查询",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/mime/",
    description: "文件扩展名与 MIME 类型互查",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "api-mock",
    name: "API Mock 生成器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/api-mock/",
    description: "根据 JSON Schema/模板生成 Mock 数据",
    inputFormats: ["json"],
    outputFormats: ["json"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "code-screenshot",
    name: "代码截图",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/code-screenshot/",
    description: "Carbon 风格代码高亮并导出图片",
    inputFormats: ["code"],
    outputFormats: ["png", "svg"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // Text
  {
    id: "text-counter",
    name: "字数统计",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/text-counter/",
    description: "文本字数、字符、行数、阅读时间统计",
    inputFormats: ["text"],
    outputFormats: ["stats"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "text-replace",
    name: "查找与替换",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/text-replace/",
    description: "支持正则与大小写的文本批量查找替换",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "text-sort",
    name: "文本排序",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/text-sort/",
    description: "行排序、去重、反转与随机重排",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "text-cleaner",
    name: "文本清理",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/text-cleaner/",
    description: "删除空行、多余空格、HTML 标签、格式整理",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "text-case",
    name: "大小写转换",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/text-case/",
    description: "大写/小写/首字母/驼峰/蛇形/短横线互转",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "chinese-convert",
    name: "简繁转换",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/chinese-convert/",
    description: "中文简体与繁体互转",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pinyin",
    name: "汉字转拼音",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/pinyin/",
    description: "汉字转拼音及声调标注",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "special-symbols",
    name: "特殊符号大全",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/special-symbols/",
    description: "特殊符号、标点、数学符号快速复制",
    inputFormats: [],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "emoji-picker",
    name: "Emoji 选择器",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/emoji-picker/",
    description: "Emoji 分类搜索与复制",
    inputFormats: [],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "word-frequency",
    name: "词频统计",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/word-frequency/",
    description: "文章词汇出现频次统计分析",
    inputFormats: ["text"],
    outputFormats: ["table"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "ascii-art",
    name: "ASCII 字符画",
    category: "Text",
    url: "https://www.wtoolskit.com/zh/ascii-art/",
    description: "图片转 ASCII 字符画",
    inputFormats: ["image"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // Image
  {
    id: "image-compressor",
    name: "图片压缩",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/image-compressor/",
    description: "客户端无损/有损图片压缩",
    inputFormats: ["jpeg", "png", "webp", "avif"],
    outputFormats: ["jpeg", "webp", "png"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-crop",
    name: "图片裁剪",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/image-crop/",
    description: "固定比例或自由裁剪图片",
    inputFormats: ["image"],
    outputFormats: ["png", "jpeg"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-resize",
    name: "图片调整尺寸",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/image-resize/",
    description: "按像素或百分比批量修改图片尺寸",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-watermark",
    name: "图片加水印",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/image-watermark/",
    description: "为图片添加文字或图片水印",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-format",
    name: "图片格式转换",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/image-format/",
    description: "PNG/JPG/WebP/AVIF 互转",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-collage",
    name: "图片拼接",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/image-collage/",
    description: "横向/纵向/网格多图拼接",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "svg-editor",
    name: "SVG 编辑器",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/svg-editor/",
    description: "SVG 代码实时编辑、优化与导出",
    inputFormats: ["svg"],
    outputFormats: ["svg", "png"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "exif-reader",
    name: "EXIF 查看与清除",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/exif-reader/",
    description: "读取和清除图片中的 EXIF 元数据",
    inputFormats: ["image"],
    outputFormats: ["metadata", "image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-ocr",
    name: "图片 OCR",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/image-ocr/",
    description: "浏览器本地文字识别 OCR",
    inputFormats: ["image"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-compare",
    name: "图片对比",
    category: "Image",
    url: "https://www.wtoolskit.com/zh/image-compare/",
    description: "滑块滑动双图差异对比",
    inputFormats: ["image"],
    outputFormats: ["preview"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // Video / Audio
  {
    id: "video-to-gif",
    name: "视频转 GIF",
    category: "Video",
    url: "https://www.wtoolskit.com/zh/video-to-gif/",
    description: "截取视频片段转为动图 GIF",
    inputFormats: ["video"],
    outputFormats: ["gif"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-trimmer",
    name: "视频裁剪",
    category: "Video",
    url: "https://www.wtoolskit.com/zh/video-trimmer/",
    description: "本地裁剪视频起止时间与画面",
    inputFormats: ["video"],
    outputFormats: ["video"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-screenshot",
    name: "视频截图",
    category: "Video",
    url: "https://www.wtoolskit.com/zh/video-screenshot/",
    description: "捕获视频当前帧为高清图片",
    inputFormats: ["video"],
    outputFormats: ["png", "jpeg"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-extract-audio",
    name: "视频提取音频",
    category: "Video",
    url: "https://www.wtoolskit.com/zh/video-extract-audio/",
    description: "从视频中提取音轨导出 MP3/WAV",
    inputFormats: ["video"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "audio-trimmer",
    name: "音频裁剪",
    category: "Audio",
    url: "https://www.wtoolskit.com/zh/audio-trimmer/",
    description: "本地裁剪音频起止时间",
    inputFormats: ["audio"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "screen-recorder",
    name: "在线录屏",
    category: "Video",
    url: "https://www.wtoolskit.com/zh/screen-recorder/",
    description: "浏览器原生 Screen Capture 录屏",
    inputFormats: [],
    outputFormats: ["webm", "mp4"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "camera-recorder",
    name: "摄像头录像",
    category: "Video",
    url: "https://www.wtoolskit.com/zh/camera-recorder/",
    description: "摄像头在线拍照与视频录制",
    inputFormats: [],
    outputFormats: ["png", "webm"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "microphone-recorder",
    name: "麦克风录音",
    category: "Audio",
    url: "https://www.wtoolskit.com/zh/microphone-recorder/",
    description: "麦克风在线录音并导出音频",
    inputFormats: [],
    outputFormats: ["wav", "webm"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "speech-to-text",
    name: "语音转文字",
    category: "Audio",
    url: "https://www.wtoolskit.com/zh/speech-to-text/",
    description: "Web Speech API 实时语音识别",
    inputFormats: ["audio"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "text-to-speech",
    name: "文字转语音",
    category: "Audio",
    url: "https://www.wtoolskit.com/zh/text-to-speech/",
    description: "SpeechSynthesis 朗读与播放",
    inputFormats: ["text"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "youtube-thumbnail",
    name: "YouTube 缩略图下载",
    category: "Video",
    url: "https://www.wtoolskit.com/zh/youtube-thumbnail/",
    description: "提取 YouTube 视频高清封面",
    inputFormats: ["url"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // PDF & Files
  {
    id: "pdf-merge",
    name: "PDF 合并",
    category: "PDF",
    url: "https://www.wtoolskit.com/zh/pdf-merge/",
    description: "合并多个 PDF 文件为一个",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-split",
    name: "PDF 拆分",
    category: "PDF",
    url: "https://www.wtoolskit.com/zh/pdf-split/",
    description: "按页码范围拆分 PDF 页面",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-watermark",
    name: "PDF 水印",
    category: "PDF",
    url: "https://www.wtoolskit.com/zh/pdf-watermark/",
    description: "为 PDF 页面添加文字/图片水印",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-to-pdf",
    name: "图片转 PDF",
    category: "PDF",
    url: "https://www.wtoolskit.com/zh/image-to-pdf/",
    description: "单张或批量图片合并生成 PDF 文档",
    inputFormats: ["image"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-to-image",
    name: "PDF 转图片",
    category: "PDF",
    url: "https://www.wtoolskit.com/zh/pdf-to-image/",
    description: "将 PDF 各页面渲染导出为 PNG/JPG",
    inputFormats: ["pdf"],
    outputFormats: ["png", "jpeg"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "zip-manager",
    name: "ZIP 压缩包管理",
    category: "Files",
    url: "https://www.wtoolskit.com/zh/zip-manager/",
    description: "在浏览器中查看、解压和创建 ZIP 包",
    inputFormats: ["zip", "files"],
    outputFormats: ["zip", "files"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "file-encryptor",
    name: "文件加密解密",
    category: "Security",
    url: "https://www.wtoolskit.com/zh/file-encryptor/",
    description: "使用 AES-GCM 本地加密解密任意文件",
    inputFormats: ["file"],
    outputFormats: ["file"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // CSS & Design
  {
    id: "css-gradient",
    name: "CSS 渐变生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/css-gradient/",
    description: "线性/径向/圆锥渐变可视化设计",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "css-filter",
    name: "CSS 滤镜生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/css-filter/",
    description: "模糊、对比度、亮度等滤镜调整与 CSS",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "css-animation",
    name: "CSS 动画生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/css-animation/",
    description: "关键帧动画可视化配置与代码导出",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "box-shadow",
    name: "Box Shadow 阴影生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/box-shadow/",
    description: "多重投影与内阴影可视化调整",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "border-radius",
    name: "Border Radius 圆角生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/border-radius/",
    description: "8值不规则圆角可视化调节",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "color-picker",
    name: "屏幕取色与调色板",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/color-picker/",
    description: "取色器与调色面板",
    inputFormats: ["color"],
    outputFormats: ["hex", "rgb", "hsl"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "color-convert",
    name: "颜色格式转换",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/color-convert/",
    description: "HEX, RGB, HSL, HSV, CMYK 互转",
    inputFormats: ["color"],
    outputFormats: ["color"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "color-palette",
    name: "图片取色调色板",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/color-palette/",
    description: "从图片自动提取主要配色方案",
    inputFormats: ["image"],
    outputFormats: ["palette"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "css-grid-generator",
    name: "CSS Grid 生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/css-grid-generator/",
    description: "网格布局可视化拖拽与 CSS",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "flexbox-generator",
    name: "Flexbox 生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/flexbox-generator/",
    description: "弹性盒模型可视化配置",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "tailwind-cheat-sheet",
    name: "Tailwind 速查",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/tailwind-cheat-sheet/",
    description: "Tailwind CSS 工具类快捷查询",
    inputFormats: ["query"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "icon-font-generator",
    name: "图标字体生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/icon-font-generator/",
    description: "SVG 图标打包为图标字体",
    inputFormats: ["svg"],
    outputFormats: ["woff2", "css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "css-bg-pattern",
    name: "CSS 背景图案生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/css-bg-pattern/",
    description: "纯 CSS 纹理与几何背景图案",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "loading-generator",
    name: "CSS 加载动画生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/loading-generator/",
    description: "丰富 Spinner 与 Loading 动画代码",
    inputFormats: ["options"],
    outputFormats: ["css", "html"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "gradient-text",
    name: "渐变文字生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/gradient-text/",
    description: "CSS 渐变字体特效与代码",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "skeleton-generator",
    name: "骨架屏生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/skeleton-generator/",
    description: "生成 Skeleton 占位加载样式",
    inputFormats: ["options"],
    outputFormats: ["css", "html"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "css-shorthand",
    name: "CSS 简写生成器",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/css-shorthand/",
    description: "margin、padding、border 简写属性生成",
    inputFormats: ["options"],
    outputFormats: ["css"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "social-share",
    name: "社交分享链接生成器",
    category: "Everyday",
    url: "https://www.wtoolskit.com/zh/social-share/",
    description: "生成各大社交平台的一键分享链接",
    inputFormats: ["url", "text"],
    outputFormats: ["url"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "social-media-sizes",
    name: "社媒尺寸参考",
    category: "Color & Design",
    url: "https://www.wtoolskit.com/zh/social-media-sizes/",
    description: "各社交平台图片与封面标准尺寸表",
    inputFormats: [],
    outputFormats: ["reference"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // Network & Utilities
  {
    id: "ip-tool",
    name: "IP 地址验证与分析",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/ip-tool/",
    description: "IPv4/IPv6 格式验证与掩码子网计算",
    inputFormats: ["text"],
    outputFormats: ["analysis"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "dns-lookup",
    name: "DNS 查询",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/dns-lookup/",
    description: "查询 A/AAAA/MX/TXT 等 DNS 记录",
    inputFormats: ["domain"],
    outputFormats: ["records"],
    processingMode: "server",
    free: true,
    requiresAuth: false,
  },
  {
    id: "speed-test",
    name: "网络测速",
    category: "Everyday",
    url: "https://www.wtoolskit.com/zh/speed-test/",
    description: "测量宽带下行速率与网络延迟",
    inputFormats: [],
    outputFormats: ["speed"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "browser-info",
    name: "浏览器信息查看",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/browser-info/",
    description: "查看 UserAgent、屏幕分辨率、硬件并发等",
    inputFormats: [],
    outputFormats: ["info"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "url-parser",
    name: "URL 解析器",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/url-parser/",
    description: "拆解 URL 协议、域名、路径与查询参数",
    inputFormats: ["url"],
    outputFormats: ["table"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "http-status",
    name: "HTTP 状态码速查",
    category: "Developer",
    url: "https://www.wtoolskit.com/zh/http-status/",
    description: "HTTP 响应状态码及原因速查",
    inputFormats: ["query"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "calculator",
    name: "标准/科学计算器",
    category: "Math",
    url: "https://www.wtoolskit.com/zh/calculator/",
    description: "标准与科学算术计算器",
    inputFormats: ["math"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "mortgage",
    name: "房贷还款计算",
    category: "Math",
    url: "https://www.wtoolskit.com/zh/mortgage/",
    description: "等额本息/等额本金房贷还款测算",
    inputFormats: ["options"],
    outputFormats: ["table"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "tax",
    name: "个税计算器",
    category: "Math",
    url: "https://www.wtoolskit.com/zh/tax/",
    description: "个人所得税及五险一金测算",
    inputFormats: ["options"],
    outputFormats: ["table"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "amount",
    name: "金额大写转换",
    category: "Math",
    url: "https://www.wtoolskit.com/zh/amount/",
    description: "阿拉伯数字金额转中文大写汉字",
    inputFormats: ["number"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-converter",
    name: "计量单位转换",
    category: "Math",
    url: "https://www.wtoolskit.com/zh/unit-converter/",
    description: "长度、重量、面积、温度等通用换算",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "date-calc",
    name: "日期计算器",
    category: "Everyday",
    url: "https://www.wtoolskit.com/zh/date-calc/",
    description: "日期间隔天数与加减计算",
    inputFormats: ["date"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "calendar",
    name: "日历查看",
    category: "Everyday",
    url: "https://www.wtoolskit.com/zh/calendar/",
    description: "公历与农历节假日日历",
    inputFormats: [],
    outputFormats: ["calendar"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "bmi",
    name: "BMI 体质指数计算",
    category: "Everyday",
    url: "https://www.wtoolskit.com/zh/bmi/",
    description: "身高体重 BMI 指数与体态评估",
    inputFormats: ["number"],
    outputFormats: ["stats"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "age",
    name: "年龄与生肖计算",
    category: "Everyday",
    url: "https://www.wtoolskit.com/zh/age/",
    description: "周岁虚岁、星座及生肖换算",
    inputFormats: ["date"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pomodoro-timer",
    name: "番茄钟计时器",
    category: "Everyday",
    url: "https://www.wtoolskit.com/zh/pomodoro-timer/",
    description: "番茄工作法 25/5 分钟计时器",
    inputFormats: [],
    outputFormats: ["timer"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "random",
    name: "随机决策器",
    category: "Everyday",
    url: "https://www.wtoolskit.com/zh/random/",
    description: "骰子/抛硬币/随机抽签与转盘",
    inputFormats: ["options"],
    outputFormats: ["result"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "hash",
    name: "SHA/MD5 哈希生成",
    category: "Security",
    url: "https://www.wtoolskit.com/zh/hash/",
    description: "MD5、SHA-1、SHA-256、SHA-512 计算",
    inputFormats: ["text", "file"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "password",
    name: "强密码生成器",
    category: "Security",
    url: "https://www.wtoolskit.com/zh/password/",
    description: "生成高强度随机密码",
    inputFormats: ["options"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "text-encrypt",
    name: "AES 文本加密解密",
    category: "Security",
    url: "https://www.wtoolskit.com/zh/text-encrypt/",
    description: "AES-CBC/GCM 密码文本加密与还原",
    inputFormats: ["text"],
    outputFormats: ["text"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "rsa-keygen",
    name: "RSA 密钥对生成",
    category: "Security",
    url: "https://www.wtoolskit.com/zh/rsa-keygen/",
    description: "生成 RSA 公钥/私钥对 (PKCS#8/SPKI)",
    inputFormats: ["options"],
    outputFormats: ["pem"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "bcrypt",
    name: "Bcrypt 密码哈希",
    category: "Security",
    url: "https://www.wtoolskit.com/zh/bcrypt/",
    description: "生成与校验 bcrypt 密码哈希值",
    inputFormats: ["text"],
    outputFormats: ["hash"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
];

const NINE_ONE_AI_ITEMS: SourceToolItem[] = [
  // Media / Video
  {
    id: "video-compress",
    name: "视频压缩",
    category: "Video",
    url: "https://www.91aitool.cn/tools/video-compress",
    description: "调整分辨率与码率压缩视频大小",
    inputFormats: ["video"],
    outputFormats: ["video"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-convert",
    name: "视频格式转换",
    category: "Video",
    url: "https://www.91aitool.cn/tools/video-convert",
    description: "MP4/WebM/MKV/AVI/FLV/MOV 互转",
    inputFormats: ["video"],
    outputFormats: ["video"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-to-audio",
    name: "视频提取音频",
    category: "Video",
    url: "https://www.91aitool.cn/tools/video-to-audio",
    description: "从视频中抽离音频导出 MP3/WAV",
    inputFormats: ["video"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-trim",
    name: "视频剪切",
    category: "Video",
    url: "https://www.91aitool.cn/tools/video-trim",
    description: "快速裁剪视频片段",
    inputFormats: ["video"],
    outputFormats: ["video"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-to-gif",
    name: "视频转 GIF",
    category: "Video",
    url: "https://www.91aitool.cn/tools/video-to-gif",
    description: "高质量视频片段转动图 GIF",
    inputFormats: ["video"],
    outputFormats: ["gif"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-speed",
    name: "视频倍速调节",
    category: "Video",
    url: "https://www.91aitool.cn/tools/video-speed",
    description: "加速或放慢视频播放速度",
    inputFormats: ["video"],
    outputFormats: ["video"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "video-rotate",
    name: "视频旋转",
    category: "Video",
    url: "https://www.91aitool.cn/tools/video-rotate",
    description: "90/180/270度调整视频朝向",
    inputFormats: ["video"],
    outputFormats: ["video"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "screen-record",
    name: "屏幕录制",
    category: "Video",
    url: "https://www.91aitool.cn/tools/screen-record",
    description: "浏览器屏幕录像与麦克风混音",
    inputFormats: [],
    outputFormats: ["webm", "mp4"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // Audio
  {
    id: "audio-to-audio",
    name: "音频格式转换",
    category: "Audio",
    url: "https://www.91aitool.cn/tools/audio-to-audio",
    description: "MP3/WAV/FLAC/AAC/OGG/M4A 互转",
    inputFormats: ["audio"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "audio-compress",
    name: "音频压缩",
    category: "Audio",
    url: "https://www.91aitool.cn/tools/audio-compress",
    description: "调整音频码率减小文件体积",
    inputFormats: ["audio"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "audio-trim",
    name: "音频裁剪",
    category: "Audio",
    url: "https://www.91aitool.cn/tools/audio-trim",
    description: "精确裁剪音乐与声音片段",
    inputFormats: ["audio"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "audio-merge",
    name: "音频拼接合并",
    category: "Audio",
    url: "https://www.91aitool.cn/tools/audio-merge",
    description: "拼接多个音频文件",
    inputFormats: ["audio"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "audio-volume",
    name: "音频音量调节",
    category: "Audio",
    url: "https://www.91aitool.cn/tools/audio-volume",
    description: "增大或减小音频分贝",
    inputFormats: ["audio"],
    outputFormats: ["audio"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // PDF
  {
    id: "pdf-merge",
    name: "PDF 合并",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-merge",
    description: "批量将多个 PDF 合为一个文件",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-split",
    name: "PDF 拆分",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-split",
    description: "按指定页码范围拆分 PDF",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-compress",
    name: "PDF 压缩",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-compress",
    description: "压缩 PDF 中的图片和流以减少体积",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-to-image",
    name: "PDF 转图片",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-to-image",
    description: "将 PDF 各页面提取为高分辨率图片",
    inputFormats: ["pdf"],
    outputFormats: ["png", "jpeg"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-to-pdf",
    name: "图片转 PDF",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/image-to-pdf",
    description: "多张图片按顺序整合打包成 PDF",
    inputFormats: ["image"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-watermark",
    name: "PDF 水印",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-watermark",
    description: "添加文字或图像防伪水印",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-rotate",
    name: "PDF 旋转",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-rotate",
    description: "调整 PDF 倒置或横向页面的方向",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-page-number",
    name: "PDF 添加页码",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-page-number",
    description: "自定义页脚页眉添加页码标注",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-extract-images",
    name: "PDF 提取图片",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-extract-images",
    description: "抽离 PDF 文档内嵌入的原始图片",
    inputFormats: ["pdf"],
    outputFormats: ["images"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-delete-pages",
    name: "PDF 页面删除",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-delete-pages",
    description: "剔除 PDF 中指定的无用页面",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-protect",
    name: "PDF 加密",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-protect",
    description: "为 PDF 增加打开和修改权限密码",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-unlock",
    name: "PDF 解密",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-unlock",
    description: "移除已知密码的 PDF 安全限制",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-to-word",
    name: "PDF 转 Word",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-to-word",
    description: "将 PDF 内容解析导出为 DOCX 文档",
    inputFormats: ["pdf"],
    outputFormats: ["docx"],
    processingMode: "server",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-to-excel",
    name: "PDF 转 Excel",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-to-excel",
    description: "提取 PDF 表格数据导出 XLSX",
    inputFormats: ["pdf"],
    outputFormats: ["xlsx"],
    processingMode: "server",
    free: true,
    requiresAuth: false,
  },
  {
    id: "pdf-to-ppt",
    name: "PDF 转 PPT",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/pdf-to-ppt",
    description: "将 PDF 转为 PPTX 幻灯片",
    inputFormats: ["pdf"],
    outputFormats: ["pptx"],
    processingMode: "server",
    free: true,
    requiresAuth: false,
  },
  {
    id: "word-to-pdf",
    name: "Word 转 PDF",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/word-to-pdf",
    description: "DOC/DOCX 排版转换并生成 PDF",
    inputFormats: ["doc", "docx"],
    outputFormats: ["pdf"],
    processingMode: "server",
    free: true,
    requiresAuth: false,
  },
  {
    id: "excel-to-pdf",
    name: "Excel 转 PDF",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/excel-to-pdf",
    description: "XLS/XLSX 工作表导出 PDF",
    inputFormats: ["xls", "xlsx"],
    outputFormats: ["pdf"],
    processingMode: "server",
    free: true,
    requiresAuth: false,
  },
  {
    id: "ppt-to-pdf",
    name: "PPT 转 PDF",
    category: "PDF",
    url: "https://www.91aitool.cn/tools/ppt-to-pdf",
    description: "PPT/PPTX 演示文稿转 PDF",
    inputFormats: ["ppt", "pptx"],
    outputFormats: ["pdf"],
    processingMode: "server",
    free: true,
    requiresAuth: false,
  },

  // Image
  {
    id: "image-compress",
    name: "图片压缩",
    category: "Image",
    url: "https://www.91aitool.cn/tools/image-compress",
    description: "智能有损/无损压缩主流图片",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-format",
    name: "图片格式转换",
    category: "Image",
    url: "https://www.91aitool.cn/tools/image-format",
    description: "JPG/PNG/WebP/BMP/GIF/ICO 互转",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-crop",
    name: "图片裁剪",
    category: "Image",
    url: "https://www.91aitool.cn/tools/image-crop",
    description: "按像素或长宽比裁剪",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-resize",
    name: "图片缩放",
    category: "Image",
    url: "https://www.91aitool.cn/tools/image-resize",
    description: "调整图片分辨率尺寸",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-watermark",
    name: "图片加水印",
    category: "Image",
    url: "https://www.91aitool.cn/tools/image-watermark",
    description: "自定义文字/半透明图片水印",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "image-exif-clean",
    name: "图片清除 EXIF",
    category: "Image",
    url: "https://www.91aitool.cn/tools/image-exif-clean",
    description: "一键抹除照片 GPS 及拍摄敏感信息",
    inputFormats: ["image"],
    outputFormats: ["image"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },

  // Units
  {
    id: "unit-length",
    name: "长度单位转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-length",
    description: "米、厘米、毫米、千米、英里、码、英尺、英寸互转",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-weight",
    name: "重量单位转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-weight",
    description: "克、千克、吨、磅、盎司、斤、两互转",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-area",
    name: "面积单位转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-area",
    description: "平方米、平方千米、公顷、市亩、平方英尺等互转",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-volume",
    name: "体积容量转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-volume",
    description: "升、毫升、立方米、加仑、品脱等互转",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-temperature",
    name: "温度单位转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-temperature",
    description: "摄氏度、华氏度、开尔文温标互转",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-time",
    name: "时间单位转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-time",
    description: "毫秒、秒、分、小时、天、周、月、年互转",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-data",
    name: "数据存储单位转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-data",
    description: "Bit, Byte, KB, MB, GB, TB, PB 换算 (1000/1024进制)",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-speed",
    name: "速度单位转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-speed",
    description: "m/s, km/h, mph, 节 (knot), 马赫互转",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-pressure",
    name: "压力单位转换",
    category: "Math",
    url: "https://www.91aitool.cn/tools/unit-pressure",
    description: "Pa, kPa, MPa, bar, psi, mmHg 换算",
    inputFormats: ["number"],
    outputFormats: ["number"],
    processingMode: "local",
    free: true,
    requiresAuth: false,
  },
];

const ONE_ZERO_ITEMS: SourceToolItem[] = [
  // Documented historical category tools from audited directory records
  {
    id: "video-audio-tools",
    name: "视频音频处理工具",
    category: "Video",
    url: "https://100016.com/video-audio",
    description: "在线视频剪辑与格式转换（历史记录，当前域名无法连接）",
    processingMode: "unknown",
    free: true,
    requiresAuth: false,
  },
  {
    id: "crypto-tools",
    name: "加密解密工具",
    category: "Security",
    url: "https://100016.com/crypto",
    description: "散列哈希与加解密实用工具（历史记录，当前域名无法连接）",
    processingMode: "unknown",
    free: true,
    requiresAuth: false,
  },
  {
    id: "text-editing-tools",
    name: "文字编辑工具",
    category: "Text",
    url: "https://100016.com/text",
    description: "文本排版与转换工具（历史记录，当前域名无法连接）",
    processingMode: "unknown",
    free: true,
    requiresAuth: false,
  },
  {
    id: "dev-tools",
    name: "编程开发工具",
    category: "Developer",
    url: "https://100016.com/dev",
    description: "代码与数据格式化工具（历史记录，当前域名无法连接）",
    processingMode: "unknown",
    free: true,
    requiresAuth: false,
  },
  {
    id: "unit-calc-tools",
    name: "单位换算工具",
    category: "Math",
    url: "https://100016.com/units",
    description: "常用度量衡与时间计算（历史记录，当前域名无法连接）",
    processingMode: "unknown",
    free: true,
    requiresAuth: false,
  },
];

export function generateSourceInventory(): MasterSourceInventory {
  return {
    generatedAt: new Date().toISOString(),
    sources: [
      {
        name: "WebTools",
        url: "https://www.wtoolskit.com/zh/",
        status: "active",
        auditNotes:
          "Successfully inspected live. Contains 117+ tools across Developer, Text, Image, Media, Files, CSS/Design, Network, Security, and Math/Utilities. High degree of client-side capability suitable for native browser and local engine integration.",
        tools: WEBTOOLS_ITEMS,
      },
      {
        name: "91AI Tools",
        url: "https://www.91aitool.cn/",
        status: "active",
        auditNotes:
          "Successfully inspected live. Contains 220+ tool endpoints with emphasis on media (video/audio compression, format conversion, trimming, extraction), PDF document manipulation (merge, split, watermark, rotate, page numbering), image utilities, and extensive unit conversion calculators. Documented distinction between client-side operations and server-dependent conversions (e.g. PDF to Word/PPT).",
        tools: NINE_ONE_AI_ITEMS,
      },
      {
        name: "100016",
        url: "https://100016.com/",
        status: "unreachable",
        auditNotes:
          "Live audit performed via HTTP fetch and DNS lookup: Domain 100016.com failed DNS resolution (no such host). Historical web directory catalog confirms previous offerings in video/audio, encryption, text editing, dev tools, unit conversion, and date calculations. Factually marked unreachable per prompt requirements without fabricating internal implementation details.",
        tools: ONE_ZERO_ITEMS,
      },
    ],
  };
}

const inventory = generateSourceInventory();
const targetPath = resolve("data/source-inventory.json");
writeFileSync(targetPath, JSON.stringify(inventory, null, 2), "utf8");
console.log(
  `✓ Master source inventory generated at ${targetPath} with ${inventory.sources.reduce((acc, s) => acc + s.tools.length, 0)} total source records across 3 ecosystems.`,
);
